### ISSUE TITLE
Korean Translation

### ISSUE THREAD

**Issue by MiryangJung** [CollabCodeTech/collabcodetraining-frontend#11]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
 I want to translating the docs into Korean.

**Describe alternatives you've considered**
None

**Additional context**
I want to translate the document so that Koreans who do not speak English well can learn about the project.
If it is okay, please let me know. :)

**Comment by joviane** [comment]
It's okay @MiryangJung.
