### ISSUE TITLE
Create component LabelCollab

### ISSUE THREAD

**Issue by MarcoBrunoBR** [CollabCodeTech/collabcodetraining-frontend#15]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Create component LabelCollab.

**Describe alternatives you've considered**
No

**Additional context**
E.g:
![imagem](https://user-images.githubusercontent.com/4096456/66445749-c1fe0480-ea3f-11e9-886b-f63704e01043.png)

Link for layout:
https://www.figma.com/file/gL5DC1W2R9zhfCRRXAjJGn/CollabWorld.training?node-id=1%3A257

**Comment by hfabio** [comment]
@MarcoBrunoBR please, check [this pull request](https://github.com/CollabCodeTech/collabcodetraining-frontend/pull/48)
