### ISSUE TITLE
Remove download video - context menu

### ISSUE THREAD

**Issue by MarcoBrunoBR** [CollabCodeTech/collabcodetraining-frontend#27]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
No

**Describe alternatives you've considered**
Remove option of the download in context menu

**Additional context**
![imagem](https://user-images.githubusercontent.com/4096456/66533515-1cb06280-eb0b-11e9-82a4-a35f69c6da4d.png)

**Comment by ChameeraD** [comment]
On it

**Comment by Pliavi** [comment]
- Remover apenas a opção de salvar o vídeo do menu de contexto é impossível*
- Impedir a abertura do menu de contexto não impede o download, pois sendo o arquivo direto passado para o navegador o usuário tem várias formas de guardá-lo:
  - Religando o contexto
  - Via plugins similares ao nosso nostálgico DownloadHelper
  - Via link da tag da mídia
  - Via source ao carregar a página
  -  Até porque só de executar o arquivo ele já está no computador da pessoa

Para que essa não seja uma opção é necessário o vídeo não pode ser distribuído como arquivo, precisaria ser via streaming/buffering, distribuindo o vídeo em partes impedindo que o navegador tenha acesso direto ao arquivo, assim como o Youtube e similares fazem.

Apesar que no fim é impossível impedir o download, mas são formas de dificultar.
A forma mais até então nesse caso é remover o menu de contexto, e se necessário só criar um personalizado.
