### ISSUE TITLE
Create ButtonCollab component

### ISSUE THREAD

**Issue by MarcoBrunoBR** [CollabCodeTech/collabcodetraining-frontend#38]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
No

**Describe alternatives you've considered**
Create ButtonCollab component

**Additional context**
![imagem](https://user-images.githubusercontent.com/4096456/66877633-1bb97e00-efae-11e9-9c15-9d4725b9e014.png)

**Comment by felipeemarcon** [comment]
I made this! https://github.com/CollabCodeTech/collabcodetraining-frontend/pull/47
