### ISSUE TITLE
Enable Git hooks for code linter 

### ISSUE THREAD

**Issue by wnqueiroz** [CollabCodeTech/collabcodetraining-frontend#6]
**Is your feature request related to a problem? Please describe.**

This feature is not related to a problem.

**Describe the solution you'd like**

This feature will help keep the code "beautiful" and standardized according to the settings defined in the project. Using Git hooks, committing the files will begin a code parsing and formatting process before adding the corresponding files to the commit.

**Describe alternatives you've considered**

None for now.

**Additional context**

None for now.

**Comment by xtealer00** [comment]
I am going to be working on a solution for it.

**Comment by imthinhvu** [comment]
Created a PR for this here: https://github.com/CollabCodeTech/collabcodetraining-frontend/pull/9

**Comment by MarcoBrunoBR** [comment]
@wnqueiroz done

**Comment by imthinhvu** [comment]
@MarcoBrunoBR - how is this done? I don't see anywhere git hooks are being used in this repository. I'm a little surprised my PR was closed without any discussion. This doesn't align with the Hacktoberfest rules, and I would argue discourages open-source contributions to this repo.
